image: node:18.12.1

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - yarn cache clean
          - yarn install --network-timeout 1000000
          - CI=false && datoApiToken=$DATO_API_TOKEN yarn build
          - pipe: atlassian/sftp-deploy:0.5.6
            variables:
              USER: 'bitbucket'
              SERVER: '161.35.28.38'
              REMOTE_PATH: '/thisisme'
              LOCAL_PATH: 'public/*'
              PASSWORD: $PASSWORD
